remote_theme: jeffreytse/jekyll-theme-yat
title: DocOps
email: your-email@domain.com
author: Johannes Hölzel

copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"
description: >- # this means to ignore newlines until "baseurl:"
  Random ramblings of an IT Veteran for future documentation purposes.
  
#baseurl: "" # the subpath of your site, e.g. /blog
url: "jhoelzel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "" # the favicon for your site

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
night_mode: "auto"
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - index.html
#   - archives.html
#   - categories.html
#   - tags.html
#   - about.md

# Build settings
# highlighter: none
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
